% using this script file to run A-Cure, three methods:
% IP-EF-SRMSE method (best of all three):IP_EF_SRMSE_func();
% IP-Spike-SRMSE method: run the file IP_Cumulative_SRMSE_func();
% IP-Cumulative-SRMSE method run the file: IP_Spike_SRMSE_func();


% run IP_EF_SRMSE method
[IP_EF_SRMSE_str_Acc, IP_EF_SRMSE_str_RMSE_clean_hfuse, IP_EF_SRMSE_str_RMSE_clean_LSQ,...
    IP_EF_SRMSE_str_RMSE_IP_EF_hfuse,IP_EF_SRMSE_str_RMSE_IP_EF_LSQ,...
    IP_EF_SRMSE_str_RMSE_Noise_hfuse, IP_EF_SRMSE_str_RMSE_Noise_LSQ, flag] = IP_EF_SRMSE_func();
fprintf('%s\n',flag);


% run IP_Cumulative_SRMSE method
[IP_Cumulative_str_Acc, IP_Cumulative_str_RMSE_Noise, IP_Cumulative_str_RMSE_Clean,...
    IP_Cumulative_str_RMSE_IP_Cumulative_SRMSE, flag] = IP_Cumulative_SRMSE_func();
fprintf('%s\n',flag);


% run IP_Spike_SRMSE method
[IP_Spike_SRMSE_str_Acc, IP_Spike_SRMSE_str_RMSE_Noise, IP_Spike_SRMSE_str_RMSE_Clean,...
    IP_Spike_SRMSE_str_RMSE_IP_Spike_SRMSE, flag] = IP_Spike_SRMSE_func();
fprintf('%s\n',flag);


% plot measles RMSE and save to file Measles_RMSE.png 
[flag] = plot_bar_reconstruction_RMSE('Measles', 1, 4, ...
    IP_Cumulative_str_RMSE_Noise,...
    IP_Cumulative_str_RMSE_IP_Cumulative_SRMSE,...
    IP_Spike_SRMSE_str_RMSE_IP_Spike_SRMSE,...
    IP_EF_SRMSE_str_RMSE_IP_EF_LSQ, ...
    IP_Cumulative_str_RMSE_Clean);
fprintf('%s\n',flag);

% plot hepatitis RMSE and save to file Hepatitis_RMSE.png 
[flag] = plot_bar_reconstruction_RMSE('Hepatitis', 5, 8, ...
    IP_Cumulative_str_RMSE_Noise,...
    IP_Cumulative_str_RMSE_IP_Cumulative_SRMSE,...
    IP_Spike_SRMSE_str_RMSE_IP_Spike_SRMSE,...
    IP_EF_SRMSE_str_RMSE_IP_EF_LSQ, ...
    IP_Cumulative_str_RMSE_Clean);
fprintf('%s\n',flag);

% plot pertussis RMSE and save to file Pertussis_RMSE.png 
[flag] = plot_bar_reconstruction_RMSE('Pertussis', 9, 12, ...
    IP_Cumulative_str_RMSE_Noise,...
    IP_Cumulative_str_RMSE_IP_Cumulative_SRMSE,...
    IP_Spike_SRMSE_str_RMSE_IP_Spike_SRMSE,...
    IP_EF_SRMSE_str_RMSE_IP_EF_LSQ, ...
    IP_Cumulative_str_RMSE_Clean);
fprintf('%s\n',flag);

% plot smallpox RMSE and save to file Smallpox_RMSE.png 
[flag] = plot_bar_reconstruction_RMSE('Smallpox', 13, 16, ...
    IP_Cumulative_str_RMSE_Noise,...
    IP_Cumulative_str_RMSE_IP_Cumulative_SRMSE,...
    IP_Spike_SRMSE_str_RMSE_IP_Spike_SRMSE,...
    IP_EF_SRMSE_str_RMSE_IP_EF_LSQ, ...
    IP_Cumulative_str_RMSE_Clean);
fprintf('%s\n',flag);
